apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-07-04T01:10:22Z
  name: sprentice.k8s.local
spec:
  additionalPolicies:
    node: |
      [
         {
           "Effect": "Allow",
           "Action": [
             "route53:ChangeResourceRecordSets"
           ],
           "Resource": [
             "arn:aws:route53:::hostedzone/*"
           ]
         },
         {
           "Effect": "Allow",
           "Action": [
             "route53:ListHostedZones",
             "route53:ListResourceRecordSets",
             "route53:ListHostedZonesByName",
             "route53:*"
           ],
           "Resource": [
             "*"
           ]
         }
       ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://sprentice-kops/sprentice.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.8
  masterInternalName: api.internal.sprentice.k8s.local
  masterPublicName: api.sprentice.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-southeast-2a
    type: Private
    zone: ap-southeast-2a
  - cidr: 172.20.64.0/19
    name: ap-southeast-2b
    type: Private
    zone: ap-southeast-2b
  - cidr: 172.20.0.0/22
    name: utility-ap-southeast-2a
    type: Utility
    zone: ap-southeast-2a
  - cidr: 172.20.4.0/22
    name: utility-ap-southeast-2b
    type: Utility
    zone: ap-southeast-2b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-07-04T01:10:22Z
  labels:
    kops.k8s.io/cluster: sprentice.k8s.local
  name: master-ap-southeast-2a
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-2a
  role: Master
  subnets:
  - ap-southeast-2a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-07-04T01:10:22Z
  labels:
    kops.k8s.io/cluster: sprentice.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: t3.micro
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-southeast-2a
  - ap-southeast-2b
