apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci
  namespace: default
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ci
    namespace: default
roleRef:
  kind: Role
  name: ci
  apiGroup: rbac.authorization.k8s.io
